AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with spring boot.

Resources:
  DematePersistFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.invest19.demat.persist.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/demat-persist-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120
      Events:
        RootResource:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  DematePersistApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: DematePersistApi
